# Default Kibana configuration for docker target
server.name: kibana
server.host: "0"
xpack.monitoring.ui.container.elasticsearch.enabled: true
server.ssl.enabled: true
server.ssl.certificate: config/certs/kibana/kibana.crt
server.ssl.key: config/certs/kibana/kibana.key
elasticsearch.hosts: ["https://elastic:9200"]
elasticsearch.username: "kibana"
elasticsearch.password: "[TODO]"
elasticsearch.ssl.certificateAuthorities: [ "config/certs/ca/ca.crt" ]