cluster.name: "docker-cluster"
network.host: 0.0.0.0
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.key: certs/elastic/elastic.key
xpack.security.http.ssl.certificate: certs/elastic/elastic.crt
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
xpack.security.transport.ssl.key: certs/elastic/elastic.key
xpack.security.transport.ssl.certificate: certs/elastic/elastic.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
